### ISSUE TITLE
Extra commented lines in main.js file

### ISSUE THREAD

**Issue by RQ16** [FACN1/week3-javiasy#42]
The several commented lines should be removed

**Comment by HilbertSpitzer** [comment]
I think you and mario are talking about the same issue: https://github.com/FACN1/week3-javiasy/issues/40

I assume you two are talking about the lines that were previously from 38-70. We have already removed them and updated the master branch by now. Or are you referring to something else? If you are then can you point to which part of the commented lines are you referring to?
Here's the new main.js:
https://github.com/FACN1/week3-javiasy/blob/50c462992d7437f936cb90377fd3954bebce22d4/main.js

**Comment by Jbarget** [comment]
@HilbertSpitzer under the "Labels" on the right hand side you can add a `duplicate` label and close this. Big 👍 for referencing the other issue that is the same

**Comment by HilbertSpitzer** [comment]
I don't want to close it without her approval
Thanks for the tip, I didn't notice that label, I appreciate it
