### ISSUE TITLE
test.js unneccessary comments

### ISSUE THREAD

**Issue by mattlub** [FACN1/week3-javiasy#46]
imho not needed: 
https://github.com/FACN1/week3-javiasy/blob/master/tests/tests.js#L21

**Comment by jwld** [comment]
We added these to avoid merge conflicts while working on the same file. But I also think it clearly separates the test file into sections, so probs wontfix, soz.

**Comment by mattlub** [comment]
woteva

**Comment by jwld** [comment]
Or did you mean just the END comment?

**Comment by mattlub** [comment]
yeh just the END ones

**Comment by jwld** [comment]
Ahh sorry, yea I agree with that. I'll take them out.
