### ISSUE TITLE
module names don't need word 'Module'

### ISSUE THREAD

**Issue by mattlub** [FACN1/week3-javiasy#48]
imho ;)

**Comment by jwld** [comment]
Hmm, it makes it clearer what's a module (as opposed to an object)

**Comment by mattlub** [comment]
I still think it's unnecessary- do you capitalise other objects?

**Comment by jwld** [comment]
That's true. Maybe in the future we won't use that syntax then - but since this is the first project using modules we'll probably leave it in for clarity for now.

**Comment by mattlub** [comment]
cool 👍
