### ISSUE TITLE
tidy up branches

### ISSUE THREAD

**Issue by Jbarget** [FACN1/week3-javiasy#55]
Looks like you can get rid of these extra branches
![screen shot 2017-03-09 at 10 46 19](https://cloud.githubusercontent.com/assets/11725595/23742491/abd93e94-04b5-11e7-8cb7-f95d76657013.png)

**Comment by macintoshhelper** [comment]
I've removed the css branch. master-pure-functions was made by me as a "snapshot" before we removed the pure functions from the code.

**Comment by Jbarget** [comment]
:+1:
